"""
AI-generated tests
Generated by asking the AI agent to "cover the project's main functionality with tests" without providing any specific testing strategy beforehand.
"""
import pytest
from application import app


@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as c:
        yield c


def make_author(client, first_name="John", last_name="Doe", nationality="American"):
    resp = client.post('/api/authors', json={
        'firstName': first_name,
        'lastName': last_name,
        'nationality': nationality,
    })
    return resp


def make_book(client, author_id, title="Test Book", user_id="11111111-1111-1111-1111-111111111111",
              genre="FICTION", year=2020, total_pages=100):
    resp = client.post('/api/books', json={
        'userId': user_id,
        'authorId': author_id,
        'title': title,
        'genre': genre,
        'publishedYear': year,
        'totalPages': total_pages,
    })
    return resp


class TestAuthorCreate:
    def test_create_author_success(self, client):
        resp = make_author(client, "George", "Orwell", "British")
        assert resp.status_code == 201
        data = resp.get_json()
        assert data['firstName'] == "George"
        assert data['lastName'] == "Orwell"
        assert 'id' in data
        assert 'createdAt' in data

    def test_create_author_missing_first_name(self, client):
        resp = client.post('/api/authors', json={'lastName': 'Doe'})
        assert resp.status_code == 400
        assert resp.get_json()['error'] == 'VALIDATION_ERROR'

    def test_create_author_missing_last_name(self, client):
        resp = client.post('/api/authors', json={'firstName': 'John'})
        assert resp.status_code == 400

    def test_create_author_empty_first_name(self, client):
        resp = client.post('/api/authors', json={'firstName': '', 'lastName': 'Doe'})
        assert resp.status_code == 400

    def test_create_author_nationality_too_long(self, client):
        resp = client.post('/api/authors', json={
            'firstName': 'John', 'lastName': 'Doe', 'nationality': 'x' * 101
        })
        assert resp.status_code == 400

    def test_create_author_without_nationality(self, client):
        resp = client.post('/api/authors', json={'firstName': 'Jane', 'lastName': 'Austen'})
        assert resp.status_code == 201
        assert resp.get_json()['nationality'] is None


class TestAuthorGet:
    def test_get_author_by_id(self, client):
        created = make_author(client, "Mark", "Twain")
        author_id = created.get_json()['id']
        resp = client.get(f'/api/authors/{author_id}')
        assert resp.status_code == 200
        assert resp.get_json()['firstName'] == "Mark"

    def test_get_author_not_found(self, client):
        resp = client.get('/api/authors/nonexistent-id')
        assert resp.status_code == 404
        assert resp.get_json()['error'] == 'NOT_FOUND'

    def test_get_authors_list(self, client):
        make_author(client, "Alpha", "One")
        make_author(client, "Beta", "Two")
        resp = client.get('/api/authors')
        assert resp.status_code == 200
        data = resp.get_json()
        assert 'data' in data
        assert 'pagination' in data

    def test_get_authors_invalid_page(self, client):
        resp = client.get('/api/authors?page=0')
        assert resp.status_code == 400

    def test_get_authors_invalid_size(self, client):
        resp = client.get('/api/authors?size=101')
        assert resp.status_code == 400

    def test_get_authors_non_integer_page(self, client):
        resp = client.get('/api/authors?page=abc')
        assert resp.status_code == 400

    def test_get_authors_search(self, client):
        make_author(client, "Searchable", "Name")
        resp = client.get('/api/authors?search=Searchable')
        assert resp.status_code == 200
        data = resp.get_json()['data']
        assert any(a['firstName'] == 'Searchable' for a in data)


class TestAuthorUpdate:
    def test_update_author_success(self, client):
        created = make_author(client, "Old", "Name")
        author_id = created.get_json()['id']
        resp = client.put(f'/api/authors/{author_id}', json={
            'firstName': 'New', 'lastName': 'Name'
        })
        assert resp.status_code == 200
        assert resp.get_json()['firstName'] == 'New'

    def test_update_author_not_found(self, client):
        resp = client.put('/api/authors/nonexistent', json={
            'firstName': 'A', 'lastName': 'B'
        })
        assert resp.status_code == 404

    def test_update_author_invalid_data(self, client):
        created = make_author(client, "Valid", "Author")
        author_id = created.get_json()['id']
        resp = client.put(f'/api/authors/{author_id}', json={'firstName': ''})
        assert resp.status_code == 400


class TestAuthorDelete:
    def test_delete_author_success(self, client):
        created = make_author(client, "ToDelete", "Author")
        author_id = created.get_json()['id']
        resp = client.delete(f'/api/authors/{author_id}')
        assert resp.status_code == 204

    def test_delete_author_not_found(self, client):
        resp = client.delete('/api/authors/nonexistent')
        assert resp.status_code == 404

    def test_delete_author_confirms_removed(self, client):
        created = make_author(client, "GoneNow", "Author")
        author_id = created.get_json()['id']
        client.delete(f'/api/authors/{author_id}')
        resp = client.get(f'/api/authors/{author_id}')
        assert resp.status_code == 404


class TestBookCreate:
    def test_create_book_success(self, client):
        author = make_author(client, "Book", "Author")
        author_id = author.get_json()['id']
        resp = make_book(client, author_id, title="1984", year=1949, total_pages=328)
        assert resp.status_code == 201
        data = resp.get_json()
        assert data['title'] == "1984"
        assert data['authorId'] == author_id

    def test_create_book_without_author(self, client):
        resp = make_book(client, author_id="nonexistent-author-id")
        assert resp.status_code == 400

    def test_create_book_missing_title(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        resp = client.post('/api/books', json={
            'userId': '11111111-1111-1111-1111-111111111111',
            'authorId': author_id,
            'genre': 'FICTION',
            'publishedYear': 2020,
            'totalPages': 100,
        })
        assert resp.status_code == 400

    def test_create_book_invalid_genre(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        resp = make_book(client, author_id, genre="INVALID_GENRE")
        assert resp.status_code == 400

    def test_create_book_invalid_year_too_old(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        resp = make_book(client, author_id, year=1000)
        assert resp.status_code == 400

    def test_create_book_negative_total_pages(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        resp = make_book(client, author_id, total_pages=-5)
        assert resp.status_code == 400

    def test_create_book_missing_user_id(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        resp = client.post('/api/books', json={
            'authorId': author_id,
            'title': 'No User',
            'genre': 'FICTION',
            'publishedYear': 2020,
            'totalPages': 100,
        })
        assert resp.status_code == 400


class TestBookGet:
    def test_get_book_by_id(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        created = make_book(client, author_id, title="Findable")
        book_id = created.get_json()['id']
        resp = client.get(f'/api/books/{book_id}')
        assert resp.status_code == 200
        assert resp.get_json()['title'] == "Findable"

    def test_get_book_not_found(self, client):
        resp = client.get('/api/books/nonexistent')
        assert resp.status_code == 404

    def test_get_books_list(self, client):
        resp = client.get('/api/books')
        assert resp.status_code == 200
        assert 'data' in resp.get_json()

    def test_get_books_invalid_sort(self, client):
        resp = client.get('/api/books?sort=invalidField')
        assert resp.status_code == 400

    def test_get_books_invalid_order(self, client):
        resp = client.get('/api/books?order=sideways')
        assert resp.status_code == 400

    def test_get_books_year_range_invalid(self, client):
        resp = client.get('/api/books?publishedYearFrom=2020&publishedYearTo=2000')
        assert resp.status_code == 400

    def test_get_books_filter_by_genre(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        make_book(client, author_id, genre="SCIENCE")
        resp = client.get('/api/books?genre=SCIENCE')
        assert resp.status_code == 200


class TestBookUpdate:
    def test_update_book_not_found(self, client):
        resp = client.put('/api/books/nonexistent', json={})
        assert resp.status_code == 404


class TestBookDelete:
    def test_delete_book_success(self, client):
        author = make_author(client)
        author_id = author.get_json()['id']
        created = make_book(client, author_id, title="ToDelete")
        book_id = created.get_json()['id']
        resp = client.delete(f'/api/books/{book_id}')
        assert resp.status_code == 204

    def test_delete_book_not_found(self, client):
        resp = client.delete('/api/books/nonexistent')
        assert resp.status_code == 404


class TestAuthorBookRelationship:
    def test_delete_author_with_books_conflict(self, client):
        author = make_author(client, "Has", "Books")
        author_id = author.get_json()['id']
        make_book(client, author_id, title="Linked Book")
        resp = client.delete(f'/api/authors/{author_id}')
        assert resp.status_code == 409
        assert resp.get_json()['error'] == 'CONFLICT'